import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const mono = Red_Hat_Mono({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={mono.className}>
      {children}
      </body>
    </html>
  );
}
